spring.application.name=Student

spring.datasource.url=jdbc:mysql://usermanagementdb.c9ggu80iw7q0.ap-south-1.rds.amazonaws.com:3306/usermanagement
spring.datasource.username=admin
spring.datasource.password=Tanisha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Tanisha@0153ggdfu123389sfgrxvhyiik1769950
jwt.expiration=3600000

groq.api.key=
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile